export const SET_LIGHT_THEME = 'THEME/SET_LIGHT';
export const SET_DARK_THEME = 'THEME/SET_DARK';


export const CREATE_ARRAY = 'ARRAY/CREATE';
export const SPEED_ONCHANGE = 'ARRAY/SPEED_ONCHANGE';
export const SET_ACTIVE = 'ARRAY/SET_ACTIVE';
export const SET_SORTED = 'ARRAY/SET_SORTED';
