export const SET_LIGHT_THEME = 'THEME/SET_LIGHT';
export const SET_DARK_THEME = 'THEME/SET_DARK';


export const CREATE_ARRAY = 'ARRAY/CREATE';
export const ARRAY_ONCHANGE = 'ARRAY/ARRAY_ONCHANGE';
export const SPEED_ONCHANGE = 'ARRAY/SPEED_ONCHANGE';
export const SET_ACTIVE = 'ARRAY/SET_ACTIVE';
export const SET_SORTED = 'ARRAY/SET_SORTED';

export const STOP_SORTING = 'STATE/STOP_SORTING';
export const SET_DISABLE_SORT_BUTTONS = 'STATE/SET_DISABLE_SORT_BUTTONS';

